import type { TazkirahItem } from '@/app/actions/tazkirah'

/* ─── 30 tazkirah entries — cycled by day-of-month ──────────────────────── */

export const TAZKIRAH_DATA: TazkirahItem[] = [
  {
    id: '2026-04-01',
    title: 'Kuasa Niat',
    content_malay: `Setiap perbuatan bermula dari niat di dalam hati. Rasulullah ﷺ bersabda bahawa semua amalan dinilai berdasarkan niatnya, dan setiap orang mendapat balasan sesuai dengan apa yang diniatkan. Dengan memperbaharui niat setiap pagi, amalan harian yang biasa dapat bertukar menjadi ibadah yang bernilai tinggi di sisi Allah.`,
    theme: 'Niat',
    category: 'Ibadat',
    color: '#102937',
    arabic_text: 'إِنَّمَا الْأَعْمَالُ بِالنِّيَّاتِ وَإِنَّمَا لِكُلِّ امْرِئٍ مَا نَوَى',
    arabic_ref: 'Hadis Riwayat al-Bukhari (no. 1)',
    muhasabah: "Apakah niatku hari ini — adakah ia benar-benar kerana Allah, atau ada unsur riya' yang perlu dibersihkan?",
    hadis_ref: 'Hadis Riwayat al-Bukhari (no. 1) dan Muslim',
    display_date: '2026-04-01',
  },
  {
    id: '2026-04-02',
    title: 'Nilai Waktu',
    content_malay: `Allah bersumpah dengan masa dalam surah Al-'Asr — satu petanda betapa berharganya waktu. Ibn al-Qayyim berkata: "Masa adalah kehidupanmu, dan kehidupanmu adalah modal utamamu." Setiap saat yang berlalu tidak akan kembali, maka gunakanlah ia dengan iman, amal soleh, saling berpesan dengan kebenaran dan kesabaran.`,
    theme: 'Masa',
    category: 'Kehidupan',
    color: '#7c3aed',
    arabic_text: 'وَالْعَصْرِ ۞ إِنَّ الْإِنسَانَ لَفِي خُسْرٍ ۞ إِلَّا الَّذِينَ آمَنُوا وَعَمِلُوا الصَّالِحَاتِ',
    arabic_ref: "Surah Al-'Asr (103:1-3)",
    muhasabah: 'Bagaimana aku akan mengisi masaku hari ini dengan sesuatu yang akan aku syukuri di hari akhirat nanti?',
    hadis_ref: null,
    display_date: '2026-04-02',
  },
  {
    id: '2026-04-03',
    title: 'Redha dengan Takdir',
    content_malay: `Apa yang menimpa kita sudah ditakdirkan sebelum kita dilahirkan. Redha bukan bermakna kita tidak berusaha — ia bermakna kita menyerahkan keputusan akhir kepada Allah dengan hati yang tenang. Jiwa yang redha adalah jiwa yang paling kaya walaupun hartanya sedikit.`,
    theme: 'Tawakkal',
    category: 'Akidah',
    color: '#0f766e',
    arabic_text: 'وَعَسَى أَن تَكْرَهُوا شَيْئًا وَهُوَ خَيْرٌ لَّكُمْ',
    arabic_ref: 'Surah Al-Baqarah (2:216)',
    muhasabah: 'Adakah aku menerima ketentuan Allah dengan hati yang lapang, atau aku masih merungut terhadap apa yang telah berlaku?',
    hadis_ref: null,
    display_date: '2026-04-03',
  },
  {
    id: '2026-04-04',
    title: 'Keajaiban Sedekah',
    content_malay: `Allah mengumpamakan sedekah seperti benih yang ditanam — satu biji menghasilkan tujuh bulir, setiap bulir pula mengandungi seratus biji. Nabi ﷺ bersabda bahawa sedekah tidak mengurangkan harta, malah ia membuka pintu rezeki dari arah yang tidak disangka-sangka. Mulailah dengan sedikit, kerana tidak ada sedekah yang terlalu kecil di sisi Allah.`,
    theme: 'Sedekah',
    category: 'Muamalat',
    color: '#ca8a04',
    arabic_text: 'مَّثَلُ الَّذِينَ يُنفِقُونَ أَمْوَالَهُمْ فِي سَبِيلِ اللَّهِ كَمَثَلِ حَبَّةٍ أَنبَتَتْ سَبْعَ سَنَابِلَ',
    arabic_ref: 'Surah Al-Baqarah (2:261)',
    muhasabah: 'Apakah kebaikan kecil yang boleh aku berikan hari ini — kepada seseorang yang memerlukan, atau kepada masjid yang amanah?',
    hadis_ref: 'Hadis Riwayat Muslim (no. 2588)',
    display_date: '2026-04-04',
  },
  {
    id: '2026-04-05',
    title: 'Kesabaran Itu Indah',
    content_malay: `Sabar bukan tanda kelemahan — ia adalah kekuatan jiwa yang luar biasa. Allah bersama orang-orang yang sabar, bermakna pertolongan-Nya sentiasa dekat. Orang yang sabar bukan sekadar menanggung kesusahan, tetapi dia terus bersyukur, tidak mengadu selain kepada Allah, dan tidak berhenti berbuat baik walaupun dalam kesakitan.`,
    theme: 'Sabar',
    category: 'Akhlak',
    color: '#1a6b52',
    arabic_text: 'إِنَّ اللَّهَ مَعَ الصَّابِرِينَ',
    arabic_ref: 'Surah Al-Baqarah (2:153)',
    muhasabah: 'Di mana dalam hidupku aku perlu lebih bersabar — dalam hubungan, dalam pekerjaan, atau dalam menanti jawapan doa?',
    hadis_ref: null,
    display_date: '2026-04-05',
  },
  {
    id: '2026-04-06',
    title: 'Jaga Lisan',
    content_malay: `Nabi ﷺ bersabda: "Sesiapa yang beriman kepada Allah dan hari akhirat, hendaklah dia berkata yang baik atau diam." Lisan yang tidak dijaga boleh meruntuhkan amal soleh bertahun-tahun dalam sekelip mata. Sebaliknya, kata-kata yang lembut dan benar adalah sedekah yang paling mudah, namun sering kita abaikan.`,
    theme: 'Lisan',
    category: 'Akhlak',
    color: '#9a3412',
    arabic_text: 'قُل لِّعِبَادِي يَقُولُوا الَّتِي هِيَ أَحْسَنُ',
    arabic_ref: "Surah Al-Isra' (17:53)",
    muhasabah: 'Pernahkah aku menyakiti hati seseorang dengan kata-kataku hari ini? Masih ada masa untuk memohon maaf.',
    hadis_ref: 'Hadis Riwayat al-Bukhari (no. 6018) dan Muslim',
    display_date: '2026-04-06',
  },
  {
    id: '2026-04-07',
    title: 'Tanda Cinta kepada Allah',
    content_malay: `Bukti cinta seorang hamba kepada Allah bukan sekadar di bibir — ia terletak pada sejauh mana dia mengikut jejak langkah Nabi ﷺ. Orang yang benar-benar mencintai Allah akan mencintai apa yang Allah cintai dan membenci apa yang Allah benci. Cinta ini mengubah cara dia makan, bercakap, bergaul, dan membuat keputusan.`,
    theme: 'Mahabbah',
    category: 'Akidah',
    color: '#5b21b6',
    arabic_text: 'قُلْ إِن كُنتُمْ تُحِبُّونَ اللَّهَ فَاتَّبِعُونِي يُحْبِبْكُمُ اللَّهُ',
    arabic_ref: "Surah Ali 'Imran (3:31)",
    muhasabah: 'Adakah cara hidupku hari ini — cara aku berbicara, bekerja, dan bergaul — mencerminkan seseorang yang benar-benar mencintai Allah?',
    hadis_ref: null,
    display_date: '2026-04-07',
  },
  {
    id: '2026-04-08',
    title: 'Kekuatan Doa',
    content_malay: `Allah berfirman: "Berdoalah kepada-Ku, nescaya Aku perkenankan." Doa adalah senjata orang mukmin. Ia bukan sekadar permintaan — ia adalah pengakuan bahawa kita lemah dan Allah Maha Berkuasa. Jangan pernah meremehkan kekuatan doa yang dipanjatkan di sepertiga malam terakhir, ketika hati dalam keadaan paling jujur.`,
    theme: 'Doa',
    category: 'Ibadat',
    color: '#0e7490',
    arabic_text: 'ادْعُونِي أَسْتَجِبْ لَكُمْ',
    arabic_ref: 'Surah Ghafir (40:60)',
    muhasabah: 'Berapa kerap aku benar-benar berdoa dengan penuh harap dan keyakinan, bukan sekadar rutiniti?',
    hadis_ref: null,
    display_date: '2026-04-08',
  },
  {
    id: '2026-04-09',
    title: 'Silaturahim: Pintu Rezeki',
    content_malay: `Nabi ﷺ bersabda bahawa sesiapa yang ingin diluaskan rezekinya dan dipanjangkan umurnya, maka hendaklah dia menyambung silaturrahim. Menziarahi ibu bapa, menghubungi saudara-mara, dan mengucapkan salam kepada jiran adalah amalan mudah yang membawa berkat yang besar. Jangan tunggu majlis istimewa — hubungi mereka hari ini.`,
    theme: 'Silaturahim',
    category: 'Muamalat',
    color: '#065f46',
    arabic_text: 'وَاتَّقُوا اللَّهَ الَّذِي تَسَاءَلُونَ بِهِ وَالْأَرْحَامَ',
    arabic_ref: "Surah An-Nisa' (4:1)",
    muhasabah: 'Siapakah ahli keluarga atau rakan lama yang sudah lama tidak aku hubungi, yang perlu aku hubungi hari ini?',
    hadis_ref: 'Hadis Riwayat al-Bukhari (no. 5985) dan Muslim',
    display_date: '2026-04-09',
  },
  {
    id: '2026-04-10',
    title: 'Ilmu yang Bermanfaat',
    content_malay: `Allah mengangkat darjat orang-orang yang beriman dan berilmu beberapa darjat. Tetapi ilmu yang paling berharga bukan sekadar yang tersimpan dalam fikiran — ia adalah ilmu yang mengubah perilaku, mendekatkan diri kepada Allah, dan memberi manfaat kepada orang lain. Tuntutlah ilmu dari buaian hingga ke liang lahad.`,
    theme: 'Ilmu',
    category: 'Kehidupan',
    color: '#1e40af',
    arabic_text: 'يَرْفَعِ اللَّهُ الَّذِينَ آمَنُوا مِنكُمْ وَالَّذِينَ أُوتُوا الْعِلْمَ دَرَجَاتٍ',
    arabic_ref: 'Surah Al-Mujadila (58:11)',
    muhasabah: 'Apakah yang aku pelajari hari ini yang membawaku lebih dekat kepada Allah dan lebih berguna kepada masyarakat?',
    hadis_ref: null,
    display_date: '2026-04-10',
  },
  {
    id: '2026-04-11',
    title: 'Sifat Malu: Mahkota Mukmin',
    content_malay: `Rasa malu adalah sebahagian daripada iman. Orang yang tiada rasa malu akan mudah melakukan apa sahaja tanpa mengira batasan agama. Malu yang dimaksudkan bukan malu untuk berbuat baik atau bercakap benar, tetapi malu terhadap Allah apabila hendak melakukan maksiat — walaupun ketika bersendirian.`,
    theme: 'Malu',
    category: 'Akhlak',
    color: '#4c1d95',
    arabic_text: null,
    arabic_ref: null,
    muhasabah: 'Adakah aku mempunyai rasa malu kepada Allah apabila aku bersendirian, sama seperti ketika bersama orang ramai?',
    hadis_ref: 'Hadis Riwayat al-Bukhari (no. 9): "Al-Haya\' min al-Iman"',
    display_date: '2026-04-11',
  },
  {
    id: '2026-04-12',
    title: 'Zikir: Penawar Hati',
    content_malay: `Allah berfirman bahawa dengan zikir kepada-Nya, hati menjadi tenteram. Dalam dunia yang penuh kekacauan dan kerisauan, zikir adalah ubat jiwa yang paling mujarab. Tidak perlu menunggu waktu tertentu — zikir boleh dilakukan sambil berjalan, bekerja, atau sebelum tidur. Lidah yang basah dengan zikir adalah lidah yang diberkati.`,
    theme: 'Zikir',
    category: 'Ibadat',
    color: '#134e4a',
    arabic_text: 'أَلَا بِذِكْرِ اللَّهِ تَطْمَئِنُّ الْقُلُوبُ',
    arabic_ref: "Surah Ar-Ra'd (13:28)",
    muhasabah: 'Berapa banyak zikir yang aku lafazkan hari ini dengan penuh kesedaran, bukan sekadar pergerakan bibir semata-mata?',
    hadis_ref: null,
    display_date: '2026-04-12',
  },
  {
    id: '2026-04-13',
    title: 'Taubat Nasuha: Pintu yang Sentiasa Terbuka',
    content_malay: `Tidak ada dosa yang terlalu besar untuk diampunkan oleh Allah, selagi nafas masih ada. Allah memanggil hamba-Nya yang berdosa agar jangan berputus asa dari rahmat-Nya. Taubat nasuha bermakna menyesal dengan sungguh-sungguh, berhenti dari dosa itu, dan berazam untuk tidak mengulanginya. Setiap hari adalah peluang baru untuk membersihkan diri.`,
    theme: 'Taubat',
    category: 'Ibadat',
    color: '#7f1d1d',
    arabic_text: 'قُلْ يَا عِبَادِيَ الَّذِينَ أَسْرَفُوا عَلَى أَنفُسِهِمْ لَا تَقْنَطُوا مِن رَّحْمَةِ اللَّهِ',
    arabic_ref: 'Surah Az-Zumar (39:53)',
    muhasabah: 'Adakah ada dosa lama yang masih membebani hatiku yang perlu aku lepaskan hari ini dengan taubat yang ikhlas?',
    hadis_ref: null,
    display_date: '2026-04-13',
  },
  {
    id: '2026-04-14',
    title: 'Syukur yang Benar',
    content_malay: `Allah berjanji bahawa jika kita bersyukur, Dia pasti menambah nikmat. Namun syukur yang benar bukan sekadar kata-kata "Alhamdulillah" — ia adalah pengakuan hati bahawa segala nikmat datang dari Allah, lisan yang memuji-Nya, dan anggota badan yang menggunakan nikmat itu dalam ketaatan. Hitung nikmat kecil hari ini — ia lebih banyak dari yang kita sedar.`,
    theme: 'Syukur',
    category: 'Akidah',
    color: '#854d0e',
    arabic_text: 'لَئِن شَكَرْتُمْ لَأَزِيدَنَّكُمْ وَلَئِن كَفَرْتُمْ إِنَّ عَذَابِي لَشَدِيدٌ',
    arabic_ref: 'Surah Ibrahim (14:7)',
    muhasabah: 'Apakah tiga nikmat hari ini yang sering aku ambil mudah namun sebenarnya merupakan anugerah Allah yang besar?',
    hadis_ref: null,
    display_date: '2026-04-14',
  },
  {
    id: '2026-04-15',
    title: 'Mengingati Mati',
    content_malay: `Setiap jiwa pasti akan merasai mati. Mengingati mati bukan untuk menjadi murung, sebaliknya untuk mendorong kita mengisi setiap saat dengan amal yang bermakna. Nabi ﷺ bersabda: "Perbanyakkanlah mengingati pemutus segala kelazatan, iaitu maut." Kematian adalah pintu menuju kepada pertemuan dengan Allah.`,
    theme: 'Mati',
    category: 'Akhirat',
    color: '#1e293b',
    arabic_text: 'كُلُّ نَفْسٍ ذَائِقَةُ الْمَوْتِ وَإِنَّمَا تُوَفَّوْنَ أُجُورَكُمْ يَوْمَ الْقِيَامَةِ',
    arabic_ref: "Surah Ali 'Imran (3:185)",
    muhasabah: 'Jika hari ini adalah hari terakhirku, apakah yang masih belum aku lakukan yang perlu aku selesaikan demi Allah?',
    hadis_ref: 'Hadis Riwayat at-Tirmidhi (no. 2307), Hasan',
    display_date: '2026-04-15',
  },
  {
    id: '2026-04-16',
    title: 'Istiqamah: Amalan Kecil yang Berterusan',
    content_malay: `Rasulullah ﷺ bersabda bahawa amalan yang paling dicintai Allah ialah amalan yang berterusan walaupun sedikit. Istiqamah tidak bermakna sempurna setiap masa — ia bermakna bangkit semula setiap kali kita terjatuh. Pohon yang berakar kukuh tidak mudah rebah dek angin ribut kehidupan.`,
    theme: 'Istiqamah',
    category: 'Ibadat',
    color: '#0f4c81',
    arabic_text: 'إِنَّ الَّذِينَ قَالُوا رَبُّنَا اللَّهُ ثُمَّ اسْتَقَامُوا',
    arabic_ref: 'Surah Fussilat (41:30)',
    muhasabah: 'Apakah satu amalan soleh kecil yang boleh aku lakukan secara istiqamah setiap hari, bermula dari hari ini?',
    hadis_ref: 'Hadis Riwayat al-Bukhari (no. 6464) dan Muslim',
    display_date: '2026-04-16',
  },
  {
    id: '2026-04-17',
    title: 'Al-Quran: Sumber Penawar',
    content_malay: `Al-Quran diturunkan sebagai penawar bagi apa yang ada dalam dada — kerisauan, kesedihan, kekeliruan, dan kesakitan jiwa. Membaca Al-Quran dengan tadabbur (penghayatan) berbeza dengan sekadar melafazkan huruf. Setiap ayat menyimpan hikmah yang boleh mengubah perspektif dan menguatkan hati.`,
    theme: 'Al-Quran',
    category: 'Ibadat',
    color: '#1e3a5f',
    arabic_text: 'وَنُنَزِّلُ مِنَ الْقُرْآنِ مَا هُوَ شِفَاءٌ وَرَحْمَةٌ لِّلْمُؤْمِنِينَ',
    arabic_ref: "Surah Al-Isra' (17:82)",
    muhasabah: 'Bilakah kali terakhir aku membaca Al-Quran dengan benar-benar memahami maknanya, bukan sekadar melepaskan tanggungjawab?',
    hadis_ref: null,
    display_date: '2026-04-17',
  },
  {
    id: '2026-04-18',
    title: 'Akhlak Nabi ﷺ: Teladan Abadi',
    content_malay: `Allah mengiktiraf akhlak Nabi Muhammad ﷺ sebagai "agung" — satu pujian tertinggi dari Pencipta kepada makhluk-Nya. Sayyidah 'Aisyah menggambarkan akhlak Nabi ﷺ sebagai "Al-Quran yang berjalan." Setiap kali kita berdepan dengan situasi sukar, tanyakan: "Bagaimanakah Nabi ﷺ akan bertindak balas dalam keadaan ini?"`,
    theme: 'Akhlak Nabi',
    category: 'Akhlak',
    color: '#312e81',
    arabic_text: 'وَإِنَّكَ لَعَلَى خُلُقٍ عَظِيمٍ',
    arabic_ref: 'Surah Al-Qalam (68:4)',
    muhasabah: 'Sifat mana dalam diri Nabi ﷺ yang paling aku perlukan untuk diterapkan dalam hidupku pada hari ini?',
    hadis_ref: "Hadis Riwayat Muslim (no. 746): 'Aisyah r.a. berkata akhlak Nabi ﷺ adalah Al-Quran",
    display_date: '2026-04-18',
  },
  {
    id: '2026-04-19',
    title: 'Kekuatan Istighfar',
    content_malay: `Nabi Nuh a.s. menyeru kaumnya untuk beristighfar kepada Allah dengan janji bahawa Dia akan menurunkan hujan lebat, menambah kekuatan, memberi anak, kebun, dan sungai. Istighfar bukan sahaja menghapus dosa — ia membuka pintu rezeki, mengangkat bala, dan mendatangkan barakah dalam setiap urusan kehidupan.`,
    theme: 'Istighfar',
    category: 'Ibadat',
    color: '#7c2d12',
    arabic_text: 'اسْتَغْفِرُوا رَبَّكُمْ إِنَّهُ كَانَ غَفَّارًا ۞ يُرْسِلِ السَّمَاءَ عَلَيْكُم مِّدْرَارًا',
    arabic_ref: 'Surah Nuh (71:10-11)',
    muhasabah: 'Sudahkah aku beristighfar hari ini — bukan sahaja untuk dosaku sendiri, tetapi juga untuk keluarga, sahabat, dan seluruh umat Islam?',
    hadis_ref: null,
    display_date: '2026-04-19',
  },
  {
    id: '2026-04-20',
    title: 'Takwa: Bekalan Terbaik',
    content_malay: `Takwa adalah perisai yang melindungi hati dari karat dosa dan penyakit jiwa. Allah menyeru kita agar berbekal dengan takwa kerana ia adalah sebaik-baik bekalan. Orang yang bertakwa melihat Allah dalam setiap tindakannya — bukan sekadar di masjid atau dalam solat, tetapi dalam setiap pilihan harian.`,
    theme: 'Takwa',
    category: 'Akidah',
    color: '#14532d',
    arabic_text: 'وَتَزَوَّدُوا فَإِنَّ خَيْرَ الزَّادِ التَّقْوَى',
    arabic_ref: 'Surah Al-Baqarah (2:197)',
    muhasabah: 'Bagaimanakah takwaku kepada Allah mempengaruhi keputusan yang aku buat hari ini — dalam perniagaan, dalam perbualan, dalam masa lapang?',
    hadis_ref: null,
    display_date: '2026-04-20',
  },
  {
    id: '2026-04-21',
    title: 'Ukhuwwah: Kekuatan Bersama',
    content_malay: `Allah memerintahkan kita untuk mendamaikan saudara seIslam yang bertelingkah. Ukhuwwah islamiyyah bukan sekadar perasaan — ia adalah tanggungjawab: mengunjungi yang sakit, membantu yang susah, mendoakan yang ghaib, dan tidak menyakiti hati mereka dengan perkataan atau perbuatan.`,
    theme: 'Ukhuwwah',
    category: 'Muamalat',
    color: '#1d4ed8',
    arabic_text: 'إِنَّمَا الْمُؤْمِنُونَ إِخْوَةٌ فَأَصْلِحُوا بَيْنَ أَخَوَيْكُمْ',
    arabic_ref: 'Surah Al-Hujurat (49:10)',
    muhasabah: 'Adakah ada saudara seIslamku yang aku tahu sedang memerlukan bantuan atau sokongan moral hari ini yang perlu aku hubungi?',
    hadis_ref: null,
    display_date: '2026-04-21',
  },
  {
    id: '2026-04-22',
    title: "Qana'ah: Kekayaan Jiwa",
    content_malay: `Rasulullah ﷺ bersabda: "Bukanlah kaya itu banyak harta, tetapi kaya yang sebenar ialah kaya hati." Qana'ah bermakna merasa cukup dengan apa yang Allah beri tanpa menghentikan usaha untuk menjadi lebih baik. Insan yang qana'ah adalah insan yang bebas — bebas dari tekanan kemewahan dan juga tekanan kekurangan.`,
    theme: "Qana'ah",
    category: 'Kehidupan',
    color: '#78350f',
    arabic_text: null,
    arabic_ref: null,
    muhasabah: 'Adakah aku mensyukuri apa yang aku miliki hari ini, atau masih terperangkap dalam keinginan yang tidak berkesudahan?',
    hadis_ref: 'Hadis Riwayat al-Bukhari (no. 6446) dan Muslim (no. 1051)',
    display_date: '2026-04-22',
  },
  {
    id: '2026-04-23',
    title: 'Husnuzon kepada Allah',
    content_malay: `Dalam hadis qudsi yang mulia, Allah berfirman: "Aku mengikut sangkaan hamba-Ku terhadap-Ku." Ini bermakna jika kita bersangka baik bahawa Allah akan menolong, mengampunkan, dan memberikan yang terbaik, maka itulah yang akan kita dapati. Jangan biarkan ujian mengaburkan keyakinan bahawa Allah sentiasa merancang kebaikan untuk hamba-Nya.`,
    theme: 'Husnuzon',
    category: 'Akidah',
    color: '#155e75',
    arabic_text: null,
    arabic_ref: null,
    muhasabah: 'Apakah sangkaanku terhadap Allah ketika menghadapi kesulitan hari ini — adakah ia sangkaan baik atau masih ada keraguan?',
    hadis_ref: 'Hadis Qudsi Riwayat al-Bukhari (no. 7505) dan Muslim',
    display_date: '2026-04-23',
  },
  {
    id: '2026-04-24',
    title: 'Berbakti kepada Ibu Bapa',
    content_malay: `Selepas kewajipan menyembah Allah, berbakti kepada ibu bapa adalah kewajipan tertinggi. Allah menyejajarkan keduanya dalam Al-Quran. Nabi ﷺ bersabda bahawa syurga berada di bawah telapak kaki ibu. Setiap hari yang mereka masih hidup adalah peluang emas yang tidak boleh disia-siakan.`,
    theme: 'Ibu Bapa',
    category: 'Muamalat',
    color: '#166534',
    arabic_text: 'وَقَضَى رَبُّكَ أَلَّا تَعْبُدُوا إِلَّا إِيَّاهُ وَبِالْوَالِدَيْنِ إِحْسَانًا',
    arabic_ref: "Surah Al-Isra' (17:23)",
    muhasabah: 'Bilakah kali terakhir aku menghubungi ibu atau bapaku semata-mata untuk memberitahu bahawa aku menyayangi mereka?',
    hadis_ref: "Hadis Riwayat an-Nasa'i (no. 3104), Sahih",
    display_date: '2026-04-24',
  },
  {
    id: '2026-04-25',
    title: 'Tafakkur dalam Ciptaan Allah',
    content_malay: `Orang-orang yang berakal (ulul albab) adalah mereka yang mengingati Allah dalam semua keadaan dan berfikir tentang ciptaan langit dan bumi. Perhatikan alam sekeliling — pergantian siang dan malam, kompleksiti tubuh manusia, keindahan alam semesta — semuanya adalah tanda-tanda yang menunjukkan kepada Pencipta Yang Maha Bijaksana.`,
    theme: 'Tafakkur',
    category: 'Akidah',
    color: '#0f4c81',
    arabic_text: 'إِنَّ فِي خَلْقِ السَّمَاوَاتِ وَالْأَرْضِ وَاخْتِلَافِ اللَّيْلِ وَالنَّهَارِ لَآيَاتٍ لِّأُولِي الْأَلْبَابِ',
    arabic_ref: "Surah Ali 'Imran (3:190)",
    muhasabah: 'Adakah aku meluangkan masa hari ini untuk sekadar berhenti seketika dan merenung kebesaran Allah dalam ciptaan-Nya?',
    hadis_ref: null,
    display_date: '2026-04-25',
  },
  {
    id: '2026-04-26',
    title: 'Tawaduk: Sifat Hamba Allah',
    content_malay: `Hamba-hamba Allah yang Maha Pemurah (Ibadur Rahman) berjalan di muka bumi dengan penuh kerendahan hati. Orang yang tawaduk bukan bermakna lemah atau merendah diri secara berlebihan — ia bermakna dia sedar bahawa segala kehebatan yang dia miliki adalah pinjaman dari Allah, dan Allah boleh mengambilnya bila-bila masa.`,
    theme: 'Tawaduk',
    category: 'Akhlak',
    color: '#1e1b4b',
    arabic_text: 'وَعِبَادُ الرَّحْمَنِ الَّذِينَ يَمْشُونَ عَلَى الْأَرْضِ هَوْنًا',
    arabic_ref: 'Surah Al-Furqan (25:63)',
    muhasabah: 'Dalam situasi mana aku cenderung bersikap sombong atau rasa lebih baik dari orang lain, yang perlu aku selesaikan dengan tawaduk?',
    hadis_ref: null,
    display_date: '2026-04-26',
  },
  {
    id: '2026-04-27',
    title: 'Memaafkan: Kunci Ketenangan',
    content_malay: `Allah suka kepada orang yang memaafkan. Menahan kemarahan dan memaafkan orang yang menyakiti kita adalah antara ciri-ciri orang bertakwa. Memaafkan bukan untuk kebaikan orang yang bersalah — ia untuk membebaskan diri kita sendiri dari beban kebencian yang meracuni jiwa.`,
    theme: 'Memaafkan',
    category: 'Akhlak',
    color: '#059669',
    arabic_text: 'وَلْيَعْفُوا وَلْيَصْفَحُوا أَلَا تُحِبُّونَ أَن يَغْفِرَ اللَّهُ لَكُمْ',
    arabic_ref: 'Surah An-Nur (24:22)',
    muhasabah: 'Adakah ada seseorang yang telah menyakiti hatiku yang perlu aku maafkan hari ini demi ketenangan jiwa dan rahmat Allah?',
    hadis_ref: null,
    display_date: '2026-04-27',
  },
  {
    id: '2026-04-28',
    title: 'Rezeki dari Allah',
    content_malay: `Tidak ada satu makhluk pun di muka bumi melainkan Allah yang menanggung rezekinya. Rezeki bukan semata-mata wang — ia merangkumi kesihatan, keluarga, ilmu, masa, dan ketenangan jiwa. Usaha adalah kewajipan kita, tetapi ketentuan hasil adalah hak Allah. Percayalah pada-Nya, kerana Dia tidak pernah ingkar janji.`,
    theme: 'Rezeki',
    category: 'Tawakkal',
    color: '#78350f',
    arabic_text: 'وَمَا مِن دَابَّةٍ فِي الْأَرْضِ إِلَّا عَلَى اللَّهِ رِزْقُهَا',
    arabic_ref: 'Surah Hud (11:6)',
    muhasabah: 'Adakah aku telah berusaha dengan sungguh-sungguh hari ini dan kemudian menyerahkan hasilnya kepada Allah dengan penuh tawakkal?',
    hadis_ref: null,
    display_date: '2026-04-28',
  },
  {
    id: '2026-04-29',
    title: 'Ikhlas: Roh Setiap Amalan',
    content_malay: `Ikhlas bermakna melakukan amalan semata-mata kerana Allah, bukan kerana ingin dipuji, ditakuti, atau disanjungi. Imam al-Fudhayl berkata: "Meninggalkan amalan kerana manusia adalah riya', dan beramal kerana manusia adalah syirik. Ikhlas itu apabila Allah sahaja yang membuatmu beramal." Satu amalan yang ikhlas lebih bernilai dari seribu amalan yang penuh riya'.`,
    theme: 'Ikhlas',
    category: 'Ibadat',
    color: '#1e3a5f',
    arabic_text: 'وَمَا أُمِرُوا إِلَّا لِيَعْبُدُوا اللَّهَ مُخْلِصِينَ لَهُ الدِّينَ',
    arabic_ref: 'Surah Al-Bayyinah (98:5)',
    muhasabah: 'Apakah amalan yang aku lakukan hari ini yang perlu aku periksa semula niatnya — adakah ia benar-benar ikhlas untuk Allah?',
    hadis_ref: null,
    display_date: '2026-04-29',
  },
  {
    id: '2026-04-30',
    title: 'Persediaan untuk Akhirat',
    content_malay: `Kehidupan dunia ibarat seorang musafir yang berehat sebentar di bawah pokok sebelum meneruskan perjalanan. Tujuan sebenar adalah akhirat — dan setiap amalan, kata-kata, dan niat hari ini akan menjadi teman di sana. Bangunkan akhiratmu seperti engkau akan hidup selama-lamanya, dan kerjakanlah duniamu seperti engkau akan mati esok.`,
    theme: 'Akhirat',
    category: 'Kehidupan',
    color: '#0f172a',
    arabic_text: 'وَمَا الْحَيَاةُ الدُّنْيَا إِلَّا مَتَاعُ الْغُرُورِ',
    arabic_ref: "Surah Ali 'Imran (3:185)",
    muhasabah: 'Apakah satu pelaburan akhirat yang boleh aku buat hari ini — ilmu yang disebarkan, doa yang dipanjatkan, atau kebaikan yang dilakukan?',
    hadis_ref: 'Hadis Riwayat Ibn Majah (no. 4259): "Bekerjalah untuk duniamu..."',
    display_date: '2026-04-30',
  },
]

/** Returns the tazkirah entry for today by cycling through the 30 entries. */
export function getTodayTazkirahFromData(): TazkirahItem {
  const dayIdx = ((new Date().getDate() - 1) % 30)
  return TAZKIRAH_DATA[dayIdx]!
}
